// AUTO-GENERATED by scripts/sync-schema.ts — do not edit by hand.
// Source: https://graphql.anilist.co introspection.
// Regenerate with: pnpm run sync-schema

import { z } from "zod";

export const MediaTypeSchema = z.enum([
  "ANIME",
  "MANGA",
]);

export const MediaFormatSchema = z.enum([
  "TV",
  "TV_SHORT",
  "MOVIE",
  "SPECIAL",
  "OVA",
  "ONA",
  "MUSIC",
  "MANGA",
  "NOVEL",
  "ONE_SHOT",
]);

export const MediaStatusSchema = z.enum([
  "FINISHED",
  "RELEASING",
  "NOT_YET_RELEASED",
  "CANCELLED",
  "HIATUS",
]);

export const MediaSeasonSchema = z.enum([
  "WINTER",
  "SPRING",
  "SUMMER",
  "FALL",
]);

export const MediaSourceSchema = z.enum([
  "ORIGINAL",
  "MANGA",
  "LIGHT_NOVEL",
  "VISUAL_NOVEL",
  "VIDEO_GAME",
  "OTHER",
  "NOVEL",
  "DOUJINSHI",
  "ANIME",
  "WEB_NOVEL",
  "LIVE_ACTION",
  "GAME",
  "COMIC",
  "MULTIMEDIA_PROJECT",
  "PICTURE_BOOK",
]);

export const MediaSortSchema = z.enum([
  "ID",
  "ID_DESC",
  "TITLE_ROMAJI",
  "TITLE_ROMAJI_DESC",
  "TITLE_ENGLISH",
  "TITLE_ENGLISH_DESC",
  "TITLE_NATIVE",
  "TITLE_NATIVE_DESC",
  "TYPE",
  "TYPE_DESC",
  "FORMAT",
  "FORMAT_DESC",
  "START_DATE",
  "START_DATE_DESC",
  "END_DATE",
  "END_DATE_DESC",
  "SCORE",
  "SCORE_DESC",
  "POPULARITY",
  "POPULARITY_DESC",
  "TRENDING",
  "TRENDING_DESC",
  "EPISODES",
  "EPISODES_DESC",
  "DURATION",
  "DURATION_DESC",
  "STATUS",
  "STATUS_DESC",
  "CHAPTERS",
  "CHAPTERS_DESC",
  "VOLUMES",
  "VOLUMES_DESC",
  "UPDATED_AT",
  "UPDATED_AT_DESC",
  "SEARCH_MATCH",
  "FAVOURITES",
  "FAVOURITES_DESC",
]);

export const ActivitySortSchema = z.enum([
  "ID",
  "ID_DESC",
  "PINNED",
]);

export const ActivityTypeSchema = z.enum([
  "TEXT",
  "ANIME_LIST",
  "MANGA_LIST",
  "MESSAGE",
  "MEDIA_LIST",
]);

export const UserTitleLanguageSchema = z.enum([
  "ROMAJI",
  "ENGLISH",
  "NATIVE",
  "ROMAJI_STYLISED",
  "ENGLISH_STYLISED",
  "NATIVE_STYLISED",
]);

export const UserStaffNameLanguageSchema = z.enum([
  "ROMAJI_WESTERN",
  "ROMAJI",
  "NATIVE",
]);

export const ScoreFormatSchema = z.enum([
  "POINT_100",
  "POINT_10_DECIMAL",
  "POINT_10",
  "POINT_5",
  "POINT_3",
]);

export const NotificationTypeSchema = z.enum([
  "ACTIVITY_MESSAGE",
  "ACTIVITY_REPLY",
  "FOLLOWING",
  "ACTIVITY_MENTION",
  "THREAD_COMMENT_MENTION",
  "THREAD_SUBSCRIBED",
  "THREAD_COMMENT_REPLY",
  "AIRING",
  "ACTIVITY_LIKE",
  "ACTIVITY_REPLY_LIKE",
  "THREAD_LIKE",
  "THREAD_COMMENT_LIKE",
  "ACTIVITY_REPLY_SUBSCRIBED",
  "RELATED_MEDIA_ADDITION",
  "MEDIA_DATA_CHANGE",
  "MEDIA_MERGE",
  "MEDIA_DELETION",
  "MEDIA_SUBMISSION_UPDATE",
  "STAFF_SUBMISSION_UPDATE",
  "CHARACTER_SUBMISSION_UPDATE",
]);

export const EntryStatusSchema = z.enum([
  "CURRENT",
  "PLANNING",
  "COMPLETED",
  "DROPPED",
  "PAUSED",
  "REPEATING",
]);

/** GraphQL types for every argument Query.Media accepts. */
export const MEDIA_FILTER_GQL_TYPES: Record<string, string> = {
  id: "Int",
  idMal: "Int",
  startDate: "FuzzyDateInt",
  endDate: "FuzzyDateInt",
  season: "MediaSeason",
  seasonYear: "Int",
  type: "MediaType",
  format: "MediaFormat",
  status: "MediaStatus",
  episodes: "Int",
  duration: "Int",
  chapters: "Int",
  volumes: "Int",
  isAdult: "Boolean",
  genre: "String",
  tag: "String",
  minimumTagRank: "Int",
  tagCategory: "String",
  onList: "Boolean",
  licensedBy: "String",
  licensedById: "Int",
  averageScore: "Int",
  popularity: "Int",
  source: "MediaSource",
  countryOfOrigin: "CountryCode",
  isLicensed: "Boolean",
  search: "String",
  id_not: "Int",
  id_in: "[Int]",
  id_not_in: "[Int]",
  idMal_not: "Int",
  idMal_in: "[Int]",
  idMal_not_in: "[Int]",
  startDate_greater: "FuzzyDateInt",
  startDate_lesser: "FuzzyDateInt",
  startDate_like: "String",
  endDate_greater: "FuzzyDateInt",
  endDate_lesser: "FuzzyDateInt",
  endDate_like: "String",
  format_in: "[MediaFormat]",
  format_not: "MediaFormat",
  format_not_in: "[MediaFormat]",
  status_in: "[MediaStatus]",
  status_not: "MediaStatus",
  status_not_in: "[MediaStatus]",
  episodes_greater: "Int",
  episodes_lesser: "Int",
  duration_greater: "Int",
  duration_lesser: "Int",
  chapters_greater: "Int",
  chapters_lesser: "Int",
  volumes_greater: "Int",
  volumes_lesser: "Int",
  genre_in: "[String]",
  genre_not_in: "[String]",
  tag_in: "[String]",
  tag_not_in: "[String]",
  tagCategory_in: "[String]",
  tagCategory_not_in: "[String]",
  licensedBy_in: "[String]",
  licensedById_in: "[Int]",
  averageScore_not: "Int",
  averageScore_greater: "Int",
  averageScore_lesser: "Int",
  popularity_not: "Int",
  popularity_greater: "Int",
  popularity_lesser: "Int",
  source_in: "[MediaSource]",
  countryOfOrigin_in: "[CountryCode]",
  countryOfOrigin_not_in: "[CountryCode]",
  sort: "[MediaSort]",
};

export const SCHEMA_SYNCED_AT = "2026-09-06";
