#!/usr/bin/env tsx
/**
 * Regenerates utils/schemas.generated.ts from live AniList introspection.
 * Run: pnpm run sync-schema
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";

const OUT = new URL("../utils/schemas.generated.ts", import.meta.url).pathname;

// AniList enum name -> our exported Zod schema name.
const ENUM_EXPORTS: Record<string, string> = {
  MediaType: "MediaTypeSchema",
  MediaFormat: "MediaFormatSchema",
  MediaStatus: "MediaStatusSchema",
  MediaSeason: "MediaSeasonSchema",
  MediaSource: "MediaSourceSchema",
  MediaSort: "MediaSortSchema",
  ActivitySort: "ActivitySortSchema",
  ActivityType: "ActivityTypeSchema",
  UserTitleLanguage: "UserTitleLanguageSchema",
  UserStaffNameLanguage: "UserStaffNameLanguageSchema",
  ScoreFormat: "ScoreFormatSchema",
  NotificationType: "NotificationTypeSchema",
  MediaListStatus: "EntryStatusSchema",
};

const QUERY = `query {
  __schema {
    types { kind name enumValues { name } }
  }
  Q: __type(name: "Query") {
    fields { name args { name type { kind name ofType { kind name ofType { kind name } } } } }
  }
}`;

function typeName(t: any): string {
  if (t.kind === "NON_NULL") return typeName(t.ofType);
  if (t.kind === "LIST") return `[${typeName(t.ofType)}]`;
  return t.name;
}

const res = await fetch("https://graphql.anilist.co", {
  method: "POST",
  headers: { "Content-Type": "application/json", Accept: "application/json" },
  body: JSON.stringify({ query: QUERY }),
});
const json: any = await res.json();
if (json.errors) throw new Error(JSON.stringify(json.errors));

const enums = new Map<string, string[]>(
  json.data.__schema.types
    .filter((t: any) => t.kind === "ENUM")
    .map((t: any) => [t.name, t.enumValues.map((v: any) => v.name)]),
);

const mediaArgs: Array<{ name: string; type: string }> = json.data.Q.fields
  .find((f: any) => f.name === "Media")
  .args.map((a: any) => ({ name: a.name, type: typeName(a.type) }));

const lines: string[] = [
  "// AUTO-GENERATED by scripts/sync-schema.ts — do not edit by hand.",
  "// Source: https://graphql.anilist.co introspection.",
  "// Regenerate with: pnpm run sync-schema",
  "",
  'import { z } from "zod";',
  "",
];

for (const [gqlName, exportName] of Object.entries(ENUM_EXPORTS)) {
  const values = enums.get(gqlName);
  if (!values) throw new Error(`AniList schema has no enum named ${gqlName}`);
  lines.push(`export const ${exportName} = z.enum([`);
  for (const v of values) lines.push(`  "${v}",`);
  lines.push("]);", "");
}

lines.push(
  "/** GraphQL types for every argument Query.Media accepts. */",
  "export const MEDIA_FILTER_GQL_TYPES: Record<string, string> = {",
);
for (const a of mediaArgs) lines.push(`  ${a.name}: "${a.type}",`);
lines.push("};", "");
lines.push(`export const SCHEMA_SYNCED_AT = "${new Date().toISOString().slice(0, 10)}";`, "");

const next = lines.join("\n");
const prev = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
writeFileSync(OUT, next);

if (!prev) {
  console.log(`created ${OUT}`);
} else if (prev === next) {
  console.log("no schema changes");
} else {
  const names = (s: string) => new Set(s.match(/^  "?[A-Za-z_]+"?[,:]/gm)?.map((x) => x.trim()) ?? []);
  const before = names(prev), after = names(next);
  for (const n of after) if (!before.has(n)) console.log(`  + ${n}`);
  for (const n of before) if (!after.has(n)) console.log(`  - ${n}`);
  console.log(`updated ${OUT}`);
}
